=== jackba/qrcode-l3info/src/Donnees/ErrorCorrectionTable.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT iso (version+) >
<!ELEMENT version (correction+) >
<!ATTLIST version number CDATA #REQUIRED>
<!ATTLIST version total_words CDATA #REQUIRED>

<!ELEMENT correction (block+) >
<!ATTLIST correction level (L|M|Q|H) #REQUIRED>
<!ATTLIST correction correction_words CDATA #REQUIRED>

<!ELEMENT block EMPTY >
<!ATTLIST block number CDATA #REQUIRED>
<!ATTLIST block total_words CDATA #REQUIRED>
<!ATTLIST block data_words CDATA #REQUIRED>
<!ATTLIST block error_words CDATA #REQUIRED>

=== jackba/qrcode-l3info/src/Donnees/ErrorCorrectionTable.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE iso SYSTEM "ErrorCorrectionTable.dtd">
<iso>
	<version number="1" total_words="26">
		<correction level="L" correction_words="7">
			<block number="1" total_words="26" data_words="19" error_words="2"/>
		</correction>
		<correction level="M" correction_words="10">
			<block number="1" total_words="26" data_words="16" error_words="4"/>
		</correction>
		<correction level="Q" correction_words="13">
			<block number="1" total_words="26" data_words="13" error_words="6"/>
		</correction>
		<correction level="H" correction_words="17">
			<block number="1" total_words="26" data_words="9" error_words="8"/>
		</correction>
	</version>
	<version number="2" total_words="44">
		<correction level="L" correction_words="10">
			<block number="1" total_words="44" data_words="34" error_words="4"/>
		</correction>
		<correction level="M" correction_words="16">
			<block number="1" total_words="44" data_words="28" error_words="8"/>
		</correction>
		<correction level="Q" correction_words="22">
			<block number="1" total_words="44" data_words="22" error_words="11"/>
		</correction>
		<correction level="H" correction_words="28">
			<block number="1" total_words="44" data_words="16" error_words="14"/>
		</correction>
	</version>
	<version number="3" total_words="70">
		<correction level="L" correction_words="15">
			<block number="1" total_words="70" data_words="55" error_words="7"/>
		</correction>
		<correction level="M" correction_words="26">
			<block number="1" total_words="70" data_words="44" error_words="13"/>
		</correction>
		<correction level="Q" correction_words="36">
			<block number="2" total_words="35" data_words="17" error_words="9"/>
		</correction>
		<correction level="H" correction_words="44">
			<block number="2" total_words="35" data_words="13" error_words="11"/>
		</correction>
	</version>
	<version number="4" total_words="100">
		<correction level="L" correction_words="20">
			<block number="1" total_words="100" data_words="80" error_words="10"/>
		</correction>
		<correction level="M" correction_words="36">
			<block number="2" total_words="50" data_words="32" error_words="9"/>
		</correction>
		<correction level="Q" correction_words="52">
			<block number="2" total_words="50" data_words="24" error_words="13"/>
		</correction>
		<correction level="H" correction_words="64">
			<block number="4" total_words="25" data_words="9" error_words="8"/>
		</correction>
	</version>
	<version number="5" total_words="134">
		<correction level="L" correction_words="26">
			<block number="1" total_words="134" data_words="108" error_words="13"/>
		</correction>
		<correction level="M" correction_words="48">
			<block number="2" total_words="67" data_words="43" error_words="12"/>
		</correction>
		<correction level="Q" correction_words="72">
			<block number="2" total_words="33" data_words="15" error_words="9"/>
			<block number="2" total_words="34" data_words="16" error_words="9"/>
		</correction>
		<correction level="H" correction_words="88">
			<block number="2" total_words="33" data_words="11" error_words="11"/>
			<block number="2" total_words="34" data_words="12" error_words="11"/>
		</correction>
	</version>
	<version number="6" total_words="172">
		<correction level="L" correction_words="36">
			<block number="2" total_words="86" data_words="68" error_words="9"/>
		</correction>
		<correction level="M" correction_words="64">
			<block number="4" total_words="43" data_words="27" error_words="8"/>
		</correction>
		<correction level="Q" correction_words="96">
			<block number="4" total_words="43" data_words="19" error_words="12"/>
		</correction>
		<correction level="H" correction_words="112">
			<block number="4" total_words="43" data_words="15" error_words="14"/>
		</correction>
	</version>
	<version number="7" total_words="196">
		<correction level="L" correction_words="40">
			<block number="2" total_words="98" data_words="78" error_words="10"/>
		</correction>
		<correction level="M" correction_words="72">
			<block number="4" total_words="49" data_words="31" error_words="9"/>
		</correction>
		<correction level="Q" correction_words="108">
			<block number="2" total_words="32" data_words="14" error_words="9"/>
			<block number="4" total_words="33" data_words="15" error_words="9"/>
		</correction>
		<correction level="H" correction_words="130">
			<block number="4" total_words="39" data_words="13" error_words="13"/>
			<block number="1" total_words="40" data_words="14" error_words="13"/>
		</correction>
	</version>
	<version number="8" total_words="242">
		<correction level="L" correction_words="48">
			<block number="2" total_words="121" data_words="97" error_words="12"/>
		</correction>
		<correction level="M" correction_words="88">
			<block number="2" total_words="60" data_words="38" error_words="11"/>
			<block number="2" total_words="61" data_words="39" error_words="11"/>
		</correction>
		<correction level="Q" correction_words="132">
			<block number="4" total_words="40" data_words="18" error_words="11"/>
			<block number="2" total_words="41" data_words="19" error_words="11"/>
		</correction>
		<correction level="H" correction_words="156">
			<block number="4" total_words="40" data_words="14" error_words="13"/>
			<block number="2" total_words="41" data_words="15" error_words="13"/>
		</correction>
	</version>
	<version number="9" total_words="292">
		<correction level="L" correction_words="60">
			<block number="2" total_words="146" data_words="116" error_words="15"/>
		</correction>
		<correction level="M" correction_words="110">
			<block number="3" total_words="58" data_words="36" error_words="11"/>
			<block number="2" total_words="59" data_words="37" error_words="11"/>
		</correction>
		<correction level="Q" correction_words="160">
			<block number="4" total_words="36" data_words="16" error_words="10"/>
			<block number="4" total_words="37" data_words="17" error_words="10"/>
		</correction>
		<correction level="H" correction_words="192">
			<block number="4" total_words="36" data_words="12" error_words="12"/>
			<block number="4" total_words="37" data_words="13" error_words="12"/>
		</correction>
	</version>
	<version number="10" total_words="346">
		<correction level="L" correction_words="72">
			<block number="2" total_words="86" data_words="68" error_words="9"/>
			<block number="2" total_words="87" data_words="69" error_words="9"/>
		</correction>
		<correction level="M" correction_words="130">
			<block number="4" total_words="69" data_words="43" error_words="13"/>
			<block number="1" total_words="70" data_words="44" error_words="13"/>
		</correction>
		<correction level="Q" correction_words="192">
			<block number="6" total_words="43" data_words="19" error_words="12"/>
			<block number="2" total_words="44" data_words="20" error_words="12"/>
		</correction>
		<correction level="H" correction_words="224">
			<block number="6" total_words="43" data_words="15" error_words="14"/>
			<block number="2" total_words="44" data_words="16" error_words="14"/>
		</correction>
	</version>
	<version number="11" total_words="404">
		<correction level="L" correction_words="80">
			<block number="4" total_words="101" data_words="81" error_words="10"/>
		</correction>
		<correction level="M" correction_words="150">
			<block number="1" total_words="80" data_words="50" error_words="15"/>
			<block number="4" total_words="81" data_words="51" error_words="15"/>
		</correction>
		<correction level="Q" correction_words="224">
			<block number="4" total_words="50" data_words="22" error_words="14"/>
			<block number="4" total_words="51" data_words="23" error_words="14"/>
		</correction>
		<correction level="H" correction_words="264">
			<block number="3" total_words="36" data_words="12" error_words="12"/>
			<block number="8" total_words="37" data_words="13" error_words="12"/>
		</correction>
	</version>
	<version number="12" total_words="466">
		<correction level="L" correction_words="96">
			<block number="2" total_words="116" data_words="92" error_words="12"/>
			<block number="2" total_words="117" data_words="93" error_words="12"/>
		</correction>
		<correction level="M" correction_words="176">
			<block number="6" total_words="58" data_words="36" error_words="11"/>
			<block number="2" total_words="59" data_words="37" error_words="11"/>
		</correction>
		<correction level="Q" correction_words="260">
			<block number="4" total_words="46" data_words="20" error_words="13"/>
			<block number="6" total_words="47" data_words="21" error_words="13"/>
		</correction>
		<correction level="H" correction_words="308">
			<block number="7" total_words="42" data_words="14" error_words="14"/>
			<block number="4" total_words="43" data_words="15" error_words="14"/>
		</correction>
	</version>
	<version number="13" total_words="532">
		<correction level="L" correction_words="104">
			<block number="4" total_words="133" data_words="107" error_words="13"/>
		</correction>
		<correction level="M" correction_words="198">
			<block number="8" total_words="59" data_words="37" error_words="11"/>
			<block number="1" total_words="60" data_words="38" error_words="11"/>
		</correction>
		<correction level="Q" correction_words="288">
			<block number="8" total_words="44" data_words="20" error_words="12"/>
			<block number="4" total_words="45" data_words="21" error_words="12"/>
		</correction>
		<correction level="H" correction_words="352">
			<block number="12" total_words="33" data_words="11" error_words="11"/>
			<block number="4" total_words="34" data_words="12" error_words="11"/>
		</correction>
	</version>
	<version number="14" total_words="581">
		<correction level="L" correction_words="120">
			<block number="3" total_words="145" data_words="115" error_words="15"/>
			<block number="1" total_words="146" data_words="116" error_words="15"/>
		</correction>
		<correction level="M" correction_words="216">
			<block number="4" total_words="64" data_words="40" error_words="12"/>
