=== jackba/qrcode-l3info/src/Donnees/numberOfSymbolCharacter.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT iso(version+) >
<!ELEMENT version(correction_level+) >

<!ELEMENT correction_level (numberBits, dataCapacity) >
<!ELEMENT number_bits (#PCDATA) >
<!ELEMENT data_capacity(numeric, alphanumeric, 8_bits_byte, kanji) >
<!ELEMENT numeric (#PCDATA)>
<!ELEMENT alphanumeric (#PCDATA)>
<!ELEMENT 8_bits_byte (#PCDATA)>
<!ELEMENT kanji (#PCDATA)>

=== jackba/qrcode-l3info/src/Donnees/numberOfSymbolCharacter.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE iso SYSTEM "numberOfSymbolCharacter.dtd">
<iso>
	<version numero="1">
		<correction_level level="L">
			<number_bits>152</number_bits>
			<data_capacity>
				<numeric>41</numeric>
				<alphanumeric>25</alphanumeric>
				<byte>17</byte>
				<kanji>10</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>128</number_bits>
			<data_capacity>
				<numeric>34</numeric>
				<alphanumeric>20</alphanumeric>
				<byte>14</byte>
				<kanji>8</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>104</number_bits>
			<data_capacity>
				<numeric>27</numeric>
				<alphanumeric>16</alphanumeric>
				<byte>11</byte>
				<kanji>7</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>72</number_bits>
			<data_capacity>
				<numeric>17</numeric>
				<alphanumeric>10</alphanumeric>
				<byte>7</byte>
				<kanji>4</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="2">
		<correction_level level="L">
			<number_bits>272</number_bits>
			<data_capacity>
				<numeric>77</numeric>
				<alphanumeric>47</alphanumeric>
				<byte>32</byte>
				<kanji>20</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>224</number_bits>
			<data_capacity>
				<numeric>63</numeric>
				<alphanumeric>38</alphanumeric>
				<byte>26</byte>
				<kanji>16</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>176</number_bits>
			<data_capacity>
				<numeric>48</numeric>
				<alphanumeric>29</alphanumeric>
				<byte>20</byte>
				<kanji>12</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>128</number_bits>
			<data_capacity>
				<numeric>34</numeric>
				<alphanumeric>20</alphanumeric>
				<byte>14</byte>
				<kanji>8</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="3">
		<correction_level level="L">
			<number_bits>440</number_bits>
			<data_capacity>
				<numeric>127</numeric>
				<alphanumeric>77</alphanumeric>
				<byte>53</byte>
				<kanji>32</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>352</number_bits>
			<data_capacity>
				<numeric>101</numeric>
				<alphanumeric>61</alphanumeric>
				<byte>42</byte>
				<kanji>26</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>272</number_bits>
			<data_capacity>
				<numeric>77</numeric>
				<alphanumeric>47</alphanumeric>
				<byte>32</byte>
				<kanji>20</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>208</number_bits>
			<data_capacity>
				<numeric>58</numeric>
				<alphanumeric>35</alphanumeric>
				<byte>24</byte>
				<kanji>15</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="4">
		<correction_level level="L">
			<number_bits>640</number_bits>
			<data_capacity>
				<numeric>187</numeric>
				<alphanumeric>114</alphanumeric>
				<byte>78</byte>
				<kanji>48</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>512</number_bits>
			<data_capacity>
				<numeric>149</numeric>
				<alphanumeric>90</alphanumeric>
				<byte>62</byte>
				<kanji>38</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>384</number_bits>
			<data_capacity>
				<numeric>111</numeric>
				<alphanumeric>67</alphanumeric>
				<byte>46</byte>
				<kanji>28</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>288</number_bits>
			<data_capacity>
				<numeric>82</numeric>
				<alphanumeric>50</alphanumeric>
				<byte>34</byte>
				<kanji>21</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="5">
		<correction_level level="L">
			<number_bits>864</number_bits>
			<data_capacity>
				<numeric>255</numeric>
				<alphanumeric>154</alphanumeric>
				<byte>106</byte>
				<kanji>65</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>688</number_bits>
			<data_capacity>
				<numeric>202</numeric>
				<alphanumeric>122</alphanumeric>
				<byte>84</byte>
				<kanji>52</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>496</number_bits>
			<data_capacity>
				<numeric>144</numeric>
				<alphanumeric>87</alphanumeric>
				<byte>60</byte>
				<kanji>37</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>468</number_bits>
			<data_capacity>
				<numeric>106</numeric>
				<alphanumeric>64</alphanumeric>
				<byte>44</byte>
				<kanji>27</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="6">
		<correction_level level="L">
			<number_bits>1088</number_bits>
			<data_capacity>
				<numeric>322</numeric>
				<alphanumeric>195</alphanumeric>
				<byte>134</byte>
				<kanji>82</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>864</number_bits>
			<data_capacity>
				<numeric>255</numeric>
				<alphanumeric>154</alphanumeric>
				<byte>106</byte>
				<kanji>65</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>608</number_bits>
			<data_capacity>
				<numeric>178</numeric>
				<alphanumeric>108</alphanumeric>
				<byte>74</byte>
				<kanji>45</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>480</number_bits>
			<data_capacity>
				<numeric>139</numeric>
				<alphanumeric>84</alphanumeric>
				<byte>58</byte>
				<kanji>36</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="7">
		<correction_level level="L">
			<number_bits>1248</number_bits>
			<data_capacity>
				<numeric>370</numeric>
				<alphanumeric>224</alphanumeric>
				<byte>154</byte>
				<kanji>95</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>992</number_bits>
			<data_capacity>
				<numeric>293</numeric>
				<alphanumeric>178</alphanumeric>
				<byte>122</byte>
				<kanji>75</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>704</number_bits>
			<data_capacity>
				<numeric>207</numeric>
				<alphanumeric>125</alphanumeric>
				<byte>86</byte>
				<kanji>53</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>528</number_bits>
			<data_capacity>
				<numeric>154</numeric>
				<alphanumeric>93</alphanumeric>
				<byte>64</byte>
				<kanji>39</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="8">
		<correction_level level="L">
			<number_bits>1552</number_bits>
			<data_capacity>
				<numeric>461</numeric>
				<alphanumeric>279</alphanumeric>
				<byte>192</byte>
				<kanji>118</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>1232</number_bits>
			<data_capacity>
				<numeric>365</numeric>
				<alphanumeric>221</alphanumeric>
				<byte>152</byte>
				<kanji>93</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>880</number_bits>
			<data_capacity>
				<numeric>259</numeric>
				<alphanumeric>157</alphanumeric>
				<byte>108</byte>
				<kanji>66</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>688</number_bits>
			<data_capacity>
				<numeric>202</numeric>
				<alphanumeric>122</alphanumeric>
				<byte>84</byte>
				<kanji>52</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="9">
		<correction_level level="L">
			<number_bits>1856</number_bits>
			<data_capacity>
				<numeric>552</numeric>
				<alphanumeric>335</alphanumeric>
				<byte>230</byte>
				<kanji>141</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>1456</number_bits>
			<data_capacity>
				<numeric>432</numeric>
				<alphanumeric>262</alphanumeric>
				<byte>180</byte>
				<kanji>111</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>1056</number_bits>
			<data_capacity>
				<numeric>312</numeric>
				<alphanumeric>189</alphanumeric>
				<byte>130</byte>
				<kanji>80</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>800</number_bits>
			<data_capacity>
				<numeric>235</numeric>
				<alphanumeric>143</alphanumeric>
				<byte>98</byte>
				<kanji>60</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="10">
		<correction_level level="L">
			<number_bits>2192</number_bits>
			<data_capacity>
				<numeric>652</numeric>
				<alphanumeric>395</alphanumeric>
				<byte>271</byte>
				<kanji>167</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="M">
			<number_bits>1728</number_bits>
			<data_capacity>
				<numeric>513</numeric>
				<alphanumeric>311</alphanumeric>
				<byte>213</byte>
				<kanji>131</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="Q">
			<number_bits>1232</number_bits>
			<data_capacity>
				<numeric>364</numeric>
				<alphanumeric>221</alphanumeric>
				<byte>151</byte>
				<kanji>93</kanji>
			</data_capacity>
		</correction_level>
		<correction_level level="H">
			<number_bits>976</number_bits>
			<data_capacity>
				<numeric>288</numeric>
				<alphanumeric>174</alphanumeric>
				<byte>119</byte>
				<kanji>74</kanji>
			</data_capacity>
		</correction_level>
	</version>
	<version numero="11">
		<correction_level level="L">
			<number_bits>2592</number_bits>
			<data_capacity>
				<numeric>772</numeric>
				<alphanumeric>468</alphanumeric>
				<byte>321</byte>
				<kanji>198</kanji>
			</data_capacity>
		</correction_level>
